name: Scheduled Workflow

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduledJob:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make build

      - name: Run
        run: ./github-project-automation
