name: Scheduled Workflow

on:
  schedule:
    - cron: "*/3 * * * *"
  workflow_dispatch:

jobs:
  scheduledJob:
    runs-on: ubuntu-latest
    env:
      CI_GITHUB_ACCESS_TOKEN: ${{ secrets.CI_GITHUB_ACCESS_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: make build

      - name: Run
        env:
          GH_TOKEN: ${{ env.CI_GITHUB_ACCESS_TOKEN }}
        run: ./github-project-automation
